/* Generated by Brickwright — blocks → C for the STC12 / 8051.
 * Regenerating from the project overwrites this file. Your edits are not
 * stuck here though — the C reader imports this back into blocks, and it
 * names anything it cannot represent rather than dropping it in silence.
 */
/* @bw-begin — machine-readable; do not hand-edit.
 * @bw device stc12c5a60s2
 * @bw clock 11059200
 * @bw pin led1 P1.0 output active-low
 * @bw script main 0 stage
 * @bw-end */
#include <stc12.h>

#define FOSC_HZ 11059200UL

/* Timer 0, mode 1, clocked at FOSC/12 — accuracy depends only on FOSC, and
 * every supported family counts this mode identically, so the same program is
 * timing-correct on a 12T STC89 and a 1T STC12 or STC15. Nothing generated here
 * ever busy-waits on a cycle count. */
#define T0_RELOAD (65536UL - (FOSC_HZ / 12UL / 1000UL))

static void delay_ms(unsigned int ms)
{
    while (ms--) {
        TL0 = (unsigned char)(T0_RELOAD & 0xFF);
        TH0 = (unsigned char)(T0_RELOAD >> 8);
        TF0 = 0;
        TR0 = 1;
        while (!TF0) ;
        TR0 = 0;
        TF0 = 0;
    }
}

/* Register setup: ports, ADC, Timer 0. Kept out of main() so the program
 * body stands alone — a C -> blocks reader can then tell them apart. */
static void bw_setup(void)
{
    P1M1 &= ~0x01;   /* push-pull */
    P1M0 |=  0x01;
    P1_0 = 1;   /* led1 off */

    AUXR &= ~0x80;                 /* Timer 0 at FOSC/12 */
    TMOD  = (TMOD & 0xF0) | 0x01;  /* Timer 0, mode 1 */
}

void main(void)
{
    bw_setup();

    // Blink SOS in Morse code: ... --- ... (dot=0.2s, dash=0.6s, gap=0.2s, letter=0.6s, word=1.4s)
    for (;;) {
        { unsigned int _i1;
            for (_i1 = 0; _i1 < (3); _i1++) {
                P1_0 = 0;
                delay_ms(200);
                P1_0 = 1;
                delay_ms(200);
            }
        }
        delay_ms(400);
        { unsigned int _i2;
            for (_i2 = 0; _i2 < (3); _i2++) {
                P1_0 = 0;
                delay_ms(600);
                P1_0 = 1;
                delay_ms(200);
            }
        }
        delay_ms(400);
        { unsigned int _i3;
            for (_i3 = 0; _i3 < (3); _i3++) {
                P1_0 = 0;
                delay_ms(200);
                P1_0 = 1;
                delay_ms(200);
            }
        }
        delay_ms(1000);
    }
}
