/* Generated by Brickwright — blocks → C for the STC12 / 8051.
 * Regenerating from the project overwrites this file. Your edits are not
 * stuck here though — the C reader imports this back into blocks, and it
 * names anything it cannot represent rather than dropping it in silence.
 */
/* @bw-begin — machine-readable; do not hand-edit.
 * @bw device stc15f2k60s2
 * @bw clock 11059200
 * @bw pin sa P0.0 output
 * @bw pin sb P0.1 output
 * @bw pin sc P0.2 output
 * @bw pin sd P0.3 output
 * @bw pin se P0.4 output
 * @bw pin sf P0.5 output
 * @bw pin sg P0.6 output
 * @bw pin sdp P0.7 output
 * @bw pin dig0 P2.0 output active-low
 * @bw pin dig1 P2.1 output active-low
 * @bw pin dig2 P2.2 output active-low
 * @bw pin vin P1.0 analog
 * @bw pin ain P1.1 analog
 * @bw pin tin P1.2 analog
 * @bw pin modeBtn P3.2 input active-low
 * @bw pin buzz P5.5 output active-low
 * @bw var d0 "d0"
 * @bw var d1 "d1"
 * @bw var d2 "d2"
 * @bw var dpDig "dpDig"
 * @bw var mode "mode"
 * @bw var lastBtn "lastBtn"
 * @bw var mv "mv"
 * @bw var cand "cand"
 * @bw var showMinus "showMinus"
 * @bw var t10 "t10"
 * @bw var diff "diff"
 * @bw var shown "shown"
 * @bw proc s0_do_clear_segments "clear segments" warp=1
 * @bw proc s0_do_render_digit "render digit %s" warp=1
 * @bw script bw_task0 0 stage
 * @bw script bw_task1 1 stage
 * @bw-end */
#include <stc12.h>

/* STC15 supplement — registers stc12.h lacks (STC15-PERIPHERAL-MODEL.md §3) */
__sbit __at (0xCC) P5_4;      /* DIP-40 pin 17, RST-shared */
__sbit __at (0xCD) P5_5;      /* DIP-40 pin 19 */
__sbit __at (0xCE) P5_6;      /* not bonded on DIP-40 */
__sbit __at (0xCF) P5_7;      /* not bonded on DIP-40 */
__sfr  __at (0xD6) T2H;       /* Timer 2 — the UART1 baud source */
__sfr  __at (0xD7) T2L;
__sfr  __at (0xBA) P_SW2;     /* peripheral pin switch 2 */
__sfr  __at (0xAA) WKTCL;     /* wake-up timer */
__sfr  __at (0xAB) WKTCH;
__sfr  __at (0xDC) CCAPM2;    /* third PCA/CCP channel */
__sfr  __at (0xEC) CCAP2L;
__sfr  __at (0xFC) CCAP2H;
__sfr  __at (0xF4) PCA_PWM2;
#define P_SW1    AUXR1        /* STC15 name for 0xA2 */
#define INT_CLKO WAKE_CLKO    /* STC15 name for 0x8F */

#define FOSC_HZ 11059200UL

/* Timer 0, mode 1, clocked at FOSC/12 — accuracy depends only on FOSC, and
 * every supported family counts this mode identically, so the same program is
 * timing-correct on a 12T STC89 and a 1T STC12 or STC15. Nothing generated here
 * ever busy-waits on a cycle count. */
#define T0_RELOAD (65536UL - (FOSC_HZ / 12UL / 1000UL))

/* One script = one cooperative task. Timer interrupts every millisecond;
 * tasks yield at every wait and at every loop iteration (Scratch's own
 * scheduling contract), so no task can starve the others. */
static volatile unsigned int bw_ms;
static unsigned char bw_calm;

void bw_tick(void) __interrupt(1)
{
    TL0 = (unsigned char)(T0_RELOAD & 0xFF);
    TH0 = (unsigned char)(T0_RELOAD >> 8);
    bw_ms++;
}

/* A 16-bit read is not atomic on an 8051; hold the tick off. */
static unsigned int bw_now(void)
{
    unsigned int t;
    ET0 = 0;
    t = bw_ms;
    ET0 = 1;
    return t;
}

/* 10-bit ADC, polled. Channel n is on P1.n; the channel is selected and the
 * conversion started in one write, as STC's own examples do. */
static long adc_read(unsigned char channel)
{
    /* Mux settle: datasheet §10.5 requires ~8 oscillator clocks after
     * channel selection.  At FOSC 11.0592 MHz that is
     * 723 ns — well under 1 µs.  The NOP loop over-provides
     * on both 1T and 12T cores: 1T gives ~32 clocks, 12T ~384. */
    ADC_CONTR = (unsigned char)(0xE8 | channel);  /* power|fast|start|chan */
    __asm nop __endasm; __asm nop __endasm;
    __asm nop __endasm; __asm nop __endasm;
    __asm nop __endasm; __asm nop __endasm;
    __asm nop __endasm; __asm nop __endasm;        /* 8 NOPs ≥ 8 osc clocks */
    while (!(ADC_CONTR & 0x10)) ;                 /* wait for ADC_FLAG */
    ADC_CONTR &= ~0x10;                           /* clear it by hand */
    return ((unsigned int)ADC_RES << 2) | (ADC_RESL & 0x03);
}

/* Variables: long, matching Scratch's number range — int is 16-bit on
 * sdcc/avr-gcc/cc65 and silently wraps mid-expression (76-multimeter). */
static long d0 = 0;
static long d1 = 0;
static long d2 = 0;
static long dpDig = 0;
static long mode = 0;
static long lastBtn = 0;
static long mv = 0;
static long cand = 0;
static long showMinus = 0;
static long t10 = 0;
static long diff = 0;
static long shown = 0;

static void s0_do_clear_segments(void);
static void s0_do_render_digit(long n);

/* clear segments */
static void s0_do_clear_segments(void)
{
    /* A Bausatz multimeter (HU-050 class), stage one: the measuring core. */
    /* Three modes on the 3-digit display, cycled by the MODE button with a */
    /* buzzer chirp: */
    /*   mode 0  volts through the 30k/10k divider      -> "X.YZ" (dp lit) */
    /*   mode 1  milliamps via 0.02R shunt + LM358 x46  -> whole mA */
    /*   mode 2  NTC via B-equation piecewise map       -> "XY.Z" degC */
    /*            (dp on the middle digit; sub-zero shows "-XY" whole degrees */
    /*            with segment g as the minus sign) */
    P0_0 = 0;
    P0_1 = 0;
    P0_2 = 0;
    P0_3 = 0;
    P0_4 = 0;
    P0_5 = 0;
    P0_6 = 0;
    P0_7 = 0;
}

/* render digit */
static void s0_do_render_digit(long n)
{
    if ((n == 0)) {
        P0_0 = 1;
        P0_1 = 1;
        P0_2 = 1;
        P0_3 = 1;
        P0_4 = 1;
        P0_5 = 1;
    }
    if ((n == 1)) {
        P0_1 = 1;
        P0_2 = 1;
    }
    if ((n == 2)) {
        P0_0 = 1;
        P0_1 = 1;
        P0_3 = 1;
        P0_4 = 1;
        P0_6 = 1;
    }
    if ((n == 3)) {
        P0_0 = 1;
        P0_1 = 1;
        P0_2 = 1;
        P0_3 = 1;
        P0_6 = 1;
    }
    if ((n == 4)) {
        P0_1 = 1;
        P0_2 = 1;
        P0_5 = 1;
        P0_6 = 1;
    }
    if ((n == 5)) {
        P0_0 = 1;
        P0_2 = 1;
        P0_3 = 1;
        P0_5 = 1;
        P0_6 = 1;
    }
    if ((n == 6)) {
        P0_0 = 1;
        P0_2 = 1;
        P0_3 = 1;
        P0_4 = 1;
        P0_5 = 1;
        P0_6 = 1;
    }
    if ((n == 7)) {
        P0_0 = 1;
        P0_1 = 1;
        P0_2 = 1;
    }
    if ((n == 8)) {
        P0_0 = 1;
        P0_1 = 1;
        P0_2 = 1;
        P0_3 = 1;
        P0_4 = 1;
        P0_5 = 1;
        P0_6 = 1;
    }
    if ((n == 9)) {
        P0_0 = 1;
        P0_1 = 1;
        P0_2 = 1;
        P0_3 = 1;
        P0_5 = 1;
        P0_6 = 1;
    }
    if ((n == 10)) {
        P0_6 = 1;
    }
}

static unsigned int bw_task0_state;
static unsigned int bw_task0_until;
/* when green flag clicked (script 1) */
static void bw_task0(void)
{
    switch (bw_task0_state) {
    case 0:
    d0 = 0;
    d1 = 0;
    d2 = 0;
    dpDig = 9;
    bw_task0_state = 1;
    case 1:
    s0_do_render_digit(d0);
    if ((dpDig == 0)) {
        P0_7 = 1;
    }
    P2_0 = 0;
    bw_task0_until = bw_now() + (2);
    bw_task0_state = 2;
    case 2:
    if ((int)(bw_now() - bw_task0_until) < 0) return;
    P2_0 = 1;
    s0_do_clear_segments();
    s0_do_render_digit(d1);
    if ((dpDig == 1)) {
        P0_7 = 1;
    }
    P2_1 = 0;
    bw_task0_until = bw_now() + (2);
    bw_task0_state = 3;
    case 3:
    if ((int)(bw_now() - bw_task0_until) < 0) return;
    P2_1 = 1;
    s0_do_clear_segments();
    s0_do_render_digit(d2);
    P2_2 = 0;
    bw_task0_until = bw_now() + (2);
    bw_task0_state = 4;
    case 4:
    if ((int)(bw_now() - bw_task0_until) < 0) return;
    P2_2 = 1;
    s0_do_clear_segments();
    bw_task0_state = 1;
    return;
    }
    bw_task0_state = 0xFFFF;   /* ran to the end */
}

static unsigned int bw_task1_state;
static unsigned int bw_task1_until;
/* when green flag clicked (script 2) */
static void bw_task1(void)
{
    switch (bw_task1_state) {
    case 0:
    mode = 0;
    lastBtn = 0;
    bw_task1_state = 1;
    case 1:
    /* the MODE button, edge-detected, with a chirp */
    if ((!P3_2 > 0)) {
        if ((lastBtn == 0)) {
            mode += 1;
            if ((mode > 2)) {
                mode = 0;
            }
            P5_5 = 0;
            bw_task1_until = bw_now() + (30);
            bw_task1_state = 2;
            case 2:
            if ((int)(bw_now() - bw_task1_until) < 0) return;
            P5_5 = 1;
        }
        lastBtn = 1;
    } else {
        lastBtn = 0;
    }
    /* take the reading for the current mode */
    if ((mode == 0)) {
        /* pin sees V/4; show centivolts as X.YZ */
        mv = ((adc_read(0) * 5000) / 1023);
        cand = ((mv * 4) / 10);
        dpDig = 0;
        showMinus = 0;
    }
    if ((mode == 1)) {
        /* LM358 output = shunt mV x 46.5; I = shunt mV x 50 */
        mv = ((adc_read(1) * 5000) / 1023);
        cand = ((mv * 50) / 47);
        dpDig = 9;
        showMinus = 0;
    }
    if ((mode == 2)) {
        /* NTC B-equation (B=3950, 10k at 25C, 10k to GND) as a piecewise */
        /* linear map over the divider millivolts; t10 = deci-degC. The */
        /* anchors are monotonic in mv, so each IF simply overwrites the */
        /* previous segment - the last match wins, no ELSE chain needed. */
        mv = ((adc_read(2) * 5000) / 1023);
        t10 = (mv - 433);
        t10 = ((t10 * 100) / 300);
        t10 = (t10 - 200);
        if ((mv > 733)) {
            t10 = (mv - 733);
            t10 = ((t10 * 100) / 413);
            t10 = (t10 - 100);
        }
        if ((mv > 1146)) {
            t10 = (mv - 1146);
            t10 = ((t10 * 100) / 511);
        }
        if ((mv > 1657)) {
            t10 = (mv - 1657);
            t10 = ((t10 * 100) / 562);
            t10 = (t10 + 100);
        }
        if ((mv > 2219)) {
            t10 = (mv - 2219);
            t10 = ((t10 * 100) / 553);
            t10 = (t10 + 200);
        }
        if ((mv > 2772)) {
            t10 = (mv - 2772);
            t10 = ((t10 * 100) / 496);
            t10 = (t10 + 300);
        }
        if ((mv > 3268)) {
            t10 = (mv - 3268);
            t10 = ((t10 * 100) / 412);
            t10 = (t10 + 400);
        }
        if ((mv > 3680)) {
            t10 = (mv - 3680);
            t10 = ((t10 * 100) / 324);
            t10 = (t10 + 500);
        }
        if ((mv > 4004)) {
            t10 = (mv - 4004);
            t10 = ((t10 * 100) / 248);
            t10 = (t10 + 600);
        }
        if ((mv > 4252)) {
            t10 = (mv - 4252);
            t10 = ((t10 * 100) / 184);
            t10 = (t10 + 700);
        }
        if ((mv > 4436)) {
            t10 = (mv - 4436);
            t10 = ((t10 * 100) / 137);
            t10 = (t10 + 800);
        }
        if ((t10 < 0)) {
            /* sub-zero: "-XY" whole degrees, minus glyph on the left digit */
            cand = (0 - t10);
            cand = (cand / 10);
            showMinus = 1;
            dpDig = 9;
        } else {
            cand = t10;
            showMinus = 0;
            dpDig = 1;
        }
    }
    if ((cand > 999)) {
        cand = 999;
    }
    diff = (cand - shown);
    if ((diff < 0)) {
        diff = (0 - diff);
    }
    if ((diff > 1)) {
        shown = cand;
        if ((showMinus == 1)) {
            d0 = 10;
            d1 = (shown / 10);
            d2 = (shown % 10);
        } else {
            d0 = (shown / 100);
            d1 = ((shown / 10) % 10);
            d2 = (shown % 10);
        }
    }
    bw_task1_until = bw_now() + (50);
    bw_task1_state = 3;
    case 3:
    if ((int)(bw_now() - bw_task1_until) < 0) return;
    bw_task1_state = 1;
    return;
    }
    bw_task1_state = 0xFFFF;   /* ran to the end */
}

/* Register setup: ports, ADC, Timer 0. Kept out of main() so the program
 * body stands alone — a C -> blocks reader can then tell them apart. */
static void bw_setup(void)
{
    P0M1 &= ~0xFF;   /* push-pull */
    P0M0 |=  0xFF;
    P2M1 &= ~0x07;   /* push-pull */
    P2M0 |=  0x07;
    P5M1 &= ~0x20;   /* push-pull */
    P5M0 |=  0x20;
    P0_0 = 0;   /* sa off */
    P0_1 = 0;   /* sb off */
    P0_2 = 0;   /* sc off */
    P0_3 = 0;   /* sd off */
    P0_4 = 0;   /* se off */
    P0_5 = 0;   /* sf off */
    P0_6 = 0;   /* sg off */
    P0_7 = 0;   /* sdp off */
    P2_0 = 1;   /* dig0 off */
    P2_1 = 1;   /* dig1 off */
    P2_2 = 1;   /* dig2 off */
    P5_5 = 1;   /* buzz off */

    P1ASF = 0x07;                 /* analog function on P1 */
    P1M1 |=  0x07;                /* high-impedance input */
    P1M0 &= ~0x07;
    ADC_CONTR = 0xE0;              /* ADC on, fastest conversion */

    AUXR &= ~0x80;                 /* Timer 0 at FOSC/12 */
    TMOD  = (TMOD & 0xF0) | 0x01;  /* Timer 0, mode 1 */
}

void main(void)
{
    bw_setup();
    TL0 = (unsigned char)(T0_RELOAD & 0xFF);
    TH0 = (unsigned char)(T0_RELOAD >> 8);
    ET0 = 1;                       /* millisecond tick */
    EA  = 1;
    TR0 = 1;

    for (;;) {                     /* the tick keeps time; the core need not */
        unsigned int pass_ms = bw_now();
        bw_task0();
        bw_task1();
        /* Two full passes inside one millisecond: idle to the next tick
         * instead of spinning the core against it — the same contract the
         * pico and AVR targets keep, spelled in the 8051's own terms.
         * PCON.IDL stops the core; Timer 0 keeps counting and its
         * interrupt clears the bit and vectors, so bw_tick above is the
         * wake source. A pass whose work crosses the edge resets the
         * count. */
        if (bw_now() == pass_ms) { if (++bw_calm >= 2u) { bw_calm = 0u; PCON |= 0x01; } }
        else bw_calm = 0u;
    }
}
